name: Build and deploy
on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    echo: "Running build"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/development') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main)'
    steps:
      - name: Download build artifacts
      - name: Deploy to staging
        if: github.ref == 'refs/heads/development'
        echo: "Running deploy to staging"
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        echo: "Running deploy to production"
